name: KelimeOyunu
version: ${project.version}
main: me.acablade.kelimeoyunu.KelimeOyunu
api-version: 1.16.4
authors: [Acablade]
description: Kelime Oyunu ama Minecraftta!
permissions:
  wordgame.game:
    description: Permission to setup word game
  wordgame.bypass:
    description: Bypasses the wordgame
commands:
  wordgame:
    description: Word game main command
